name: 🚀 Feature Request
description: Suggest an improvement or new feature
title: "[Feature]: "
labels: ["enhancement"]
assignees: ["Nicxe"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part should be improved?
      options:
        - Integration
        - Card
        - Both
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to Solve
      description: What problem does this feature address?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should it work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative approaches?
